# Generated by Django 4.0.3 on 2022-06-14 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_preference_alter_news_options_alter_share_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='share',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 9, 47, 36, 218435), verbose_name='date_added'),
        ),
    ]
