# Generated by Django 4.0.6 on 2022-07-19 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_alter_newskeyword_options_alter_preference_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='default_value',
            field=models.TextField(null=True, verbose_name='default_value'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='share',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 9, 19, 43, 506163), verbose_name='date_added'),
        ),
    ]
